
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BOOL CHAR COLON EQUALS FLOAT ID INT SEMICOLON STRING\n    declaration : type ID EQUALS value SEMICOLON\n    \n    type : INT\n         | FLOAT\n         | BOOL\n         | CHAR\n         | STRING\n    \n    value : INT\n          | FLOAT\n          | BOOL\n          | CHAR\n          | STRING\n    '
    
_lr_action_items = {'INT':([0,9,],[3,11,]),'FLOAT':([0,9,],[4,12,]),'BOOL':([0,9,],[5,13,]),'CHAR':([0,9,],[6,14,]),'STRING':([0,9,],[7,15,]),'$end':([1,16,],[0,-1,]),'ID':([2,3,4,5,6,7,],[8,-2,-3,-4,-5,-6,]),'EQUALS':([8,],[9,]),'SEMICOLON':([10,11,12,13,14,15,],[16,-7,-8,-9,-10,-11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'declaration':([0,],[1,]),'type':([0,],[2,]),'value':([9,],[10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> declaration","S'",1,None,None,None),
  ('declaration -> type ID EQUALS value SEMICOLON','declaration',5,'p_declaration','test.py',42),
  ('type -> INT','type',1,'p_type','test.py',48),
  ('type -> FLOAT','type',1,'p_type','test.py',49),
  ('type -> BOOL','type',1,'p_type','test.py',50),
  ('type -> CHAR','type',1,'p_type','test.py',51),
  ('type -> STRING','type',1,'p_type','test.py',52),
  ('value -> INT','value',1,'p_value','test.py',58),
  ('value -> FLOAT','value',1,'p_value','test.py',59),
  ('value -> BOOL','value',1,'p_value','test.py',60),
  ('value -> CHAR','value',1,'p_value','test.py',61),
  ('value -> STRING','value',1,'p_value','test.py',62),
]
