xxxbule = ['mom', '18 year old', 'teen', 'taboo', 'old and young', 'mature', 'reality', 'shemale', 'fantasy', 'anal', 'german', 'lesbian', 'granny', 'retro', 'stepmom', 'amateur', 'humiliation', 'rough sex', 'outdoor', 'step fantasy', 'gangbang', 'cum swallowing', 'dad', 'celebrity', 'compilation', 'tranny', 'creampie', 'wife', 'japanese', 'saggy tits', 'group sex', 'hidden camera', 'orgasm', 'nudist', 'cartoon', 'handjob', 'big cock', 'french', 'tight pussy', 'cuckold', 'hairy', 'voyeur', 'big tits', 'cfnm', 'double penetration', 'skinny', 'massage', 'pissing', 'homemade', 'toys', 'doctor', 'masturbating', 'threesome', 'orgy', 'cumshot', 'bdsm', 'milf', 'gay', 'midget', 'beach']

pornicom = ['amateur', 'anal', 'asian', 'ass', 'babe', 'babysitter', 'bbw', 'big ass', 'big dick', 'big tits', 'bikini', 'bisexual', 'black', 'black hair', 'blonde', 'blowjob', 'brunette', 'bukkake', 'busty', 'coed', 'creampie', 'cumshots', 'domination', 'dp', 'ebony', 'european', 'fetish', 'foot', 'gangbang', 'gf', 'hairy', 'handjob', 'hardcore', 'hd', 'hentai', 'indian', 'interracial', 'japanese', 'kissing', 'latina', 'lesbian', 'lingerie', 'massage', 'masturbation', 'mature', 'midget', 'milf', 'orgy', 'outdoor', 'pantyhose']


pervclips = ['amateur', 'anal', 'asian', 'ass', 'babe', 'bbw', 'big ass', 'big dick', 'big tits', 'bisexual', 'black', 'blonde', 'blowjob', 'brunette', 'bukkake', 'coed', 'creampie', 'cumshots', 'dp', 'ebony', 'european', 'fetish', 'fisting', 'foot', 'gangbang', 'gf', 'hairy', 'handjob', 'hardcore', 'hd', 'hentai', 'indian', 'interracial', 'japanese', 'kissing', 'latina', 'lesbian', 'massage', 'masturbation', 'mature', 'milf', 'orgy', 'outdoor', 'pantyhose', 'playboy', 'pornstar', 'pov', 'reality', 'redhead', 'rimming', 'rough sex', 'shaved', 'shemale / tranny', 'small tits', 'solo girl', 'squirting', 'stockings', 'teen (18+)', 'threesome', 'toys']



pornwhite = ['18+', '3d', 'amateur', 'anal', 'ass', 'babe', 'big tits', 'black', 'blowjob', 'casting', 'creampie', 'cumshot', 'ebony', 'european', 'fetish', 'gf', 'hardcore', 'hd', 'hentai', 'japanese', 'latina', 'lesbian', 'massage', 'milf', 'mom', 'orgy', 'outdoors', 'petite', 'pornstar', 'pov', 'rimming', 'shemale / tranny', 'solo', 'teen (18+)', 'toys', 'vintage']


vikiporn = ['amateur', 'american', 'anal', 'anime', 'asian', 'ass', 'babe', 'bbw', 'beautiful', 'big cock', 'big tits', 'bisexual', 'black', 'blonde', 'blowjob', 'brunette', 'bukkake', 'camel toe hoes', 'creampie', 'cumshots', 'dad', 'domination', 'dp', 'european', 'fetish', 'fisting', 'foot', 'fully clothed sex', 'girlfriend', 'gonzo', 'hairy', 'handjob', 'hardcore', 'hd', 'interracial', 'japanese', 'kissing', 'latina', 'lesbian', 'lingerie', 'massage', 'masturbation', 'mature', 'milf', 'orgy', 'outdoor', 'petite', 'playboy', 'pornstar', 'pov']


cats = ['girlfriend', 'reality', 'compilation', 'big ass', '18+', 'latina', 'shemale / tranny', 'saggy tits', 'fisting', 'stockings', 'nudist', 'bisexual', 'japanese', 'blowjob', 'rimming', 'cumshot', 'shaved', 'threesome', 'big tits', 'masturbation', 'brunette', 'fully clothed sex', 'squirting', 'hidden camera', 'coed', 'retro', 'playboy', 'hd', 'pornstar', 'mature', '3d', 'celebrity', 'kissing', 'babe', 'massage', 'big cock', 'pantyhose', 'cuckold', 'american', 'milf', 'hentai', 'babysitter', 'teen', 'bdsm', 'lesbian', 'skinny', 'cfnm', 'amateur', 'fetish', 'masturbating', 'interracial', 'creampie', 'domination', 'stepmom', 'pov', 'solo', 'european', 'voyeur', 'indian', 'anime', 'lingerie', 'anal', 'double penetration', 'bbw', 'small tits', 'orgasm', 'gf', 'midget', 'orgy', 'outdoors', 'busty', 'old and young', 'wife', 'beach', 'bukkake', 'outdoor', 'solo girl', 'foot', 'cumshots', 'fantasy', 'humiliation', 'dad', 'shemale', 'rough sex', 'camel toe hoes', 'black hair', 'gangbang', 'german', 'petite', 'granny', 'tight pussy', 'cartoon', 'doctor', 'asian', 'hardcore', 'big dick', 'gay', 'mom', 'hairy', 'pissing', 'blonde', 'beautiful', 'group sex', 'cum swallowing', 'black', 'dp', 'taboo', 'ebony', 'teen (18+)', 'homemade', 'redhead', 'step fantasy', 'gonzo', 'vintage', 'french', 'casting', 'tranny', 'bikini', 'ass', '18 year old', 'handjob', 'toys']